language: go

go:
  - "1.x"
  - "1.8"
  - "1.10.x"
  - master

before_install:
  # Install golint
  - go get -u github.com/golang/lint/golint

install:
  # Fetch all dependencies
  - go get -t ./...

script:
  # Ensure code passes all lint tests
  - golint -set_exit_status

  # Check for common Go application problems with 'go tool vet'
  - go tool vet .

  # Run all tests included with our application
  - go test ./...